# version: '3'

services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: bdbeebit
      DATABASE_PASSWORD: esp93w5438
      DATABASE_NAME: beebit
    ports:
      - "4000:4000"
    depends_on:
      - db


  db:
    image: postgres:17
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: bdbeebit
      POSTGRES_PASSWORD: esp93w5438
      POSTGRES_DB: beebit
    ports:
      - "5432:5432"


