#version: "3"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - db
    environment:
      BACKEND_API_URL: http://backend:4000/api 
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bdbeebit:esp93w5438@db:5432/beebit
    networks:
      - app-network


  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: bdbeebit
      POSTGRES_PASSWORD: esp93w5438
      POSTGRES_DB: beebit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
