FROM node:18-alpine AS builder

WORKDIR /app

COPY ./package*.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY ./ .  

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app . 

RUN npm install --only=production

EXPOSE 3001

CMD ["npm", "start"]
