# Usamos una imagen de Node.js
FROM node:18-alpine AS builder

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de package.json e installamos las dependencias
COPY package*.json ./
RUN npm install

# Copiamos el código fuente
COPY . .

# Compilamos el código TypeScript
RUN npm run build

# Usamos una segunda etapa para crear una imagen más pequeña
FROM node:18-alpine AS production
WORKDIR /app

# Copiamos las dependencias de producción y el código compilado
COPY --from=builder /app .

# Instalar solo dependencias de producción
RUN npm install --only=production

# Ejecutar la aplicación
CMD ["node", "dist/main"]
