import { MigrationInterface, QueryRunner } from "typeorm";

export class AddEmpresaUuid1729670351999 implements MigrationInterface {
    name = 'AddEmpresaUuid1729670351999'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "proyecto_empresa_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP CONSTRAINT "fk_proyecto"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP CONSTRAINT "fk_empleado"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "fk_empresa"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "fk_empresa_staff"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "proyecto_pkey"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "uuid"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "empresa_id"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP CONSTRAINT "tarea_pkey"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "uuid"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "fechainicio"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "fechafin"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "proyecto_id"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "empleado_id"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "empleado_pkey"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "uuid"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "fechacontratacion"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "empresa_id"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "staff_pkey"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "uuid"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "empresa_id"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "empresa_pkey"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "uuid"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "PK_589bf061fd654da7076e68e1699" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "empresaId" uuid`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD CONSTRAINT "PK_52df0f8fc74f81d0531ad890f0e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "fechaInicio" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "fechaFin" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "proyectoId" uuid`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "empleadoId" uuid`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "PK_d15e7688d5ed23e9fdb570b2e5d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "fechaContratacion" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "empresaId" uuid`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "PK_e4ee98bb552756c180aec1e854a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "empresaId" uuid`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "PK_bee78e8f1760ccf9cff402118a6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "descripcion" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ALTER COLUMN "fecha_inicio" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ALTER COLUMN "fecha_fin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ALTER COLUMN "presupuesto" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "estado" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "descripcion" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "estado" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "apellidos"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "apellidos" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "empleado_email_key"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "telefono" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "empleado_username_key"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "UQ_672277994ca3023846620f5c7a2" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "apellidos"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "apellidos" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "staff_email_key"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "UQ_902985a964245652d5e3a0f5f6a" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "telefono" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "puesto"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "puesto" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "staff_username_key"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "UQ_35aafb5ad218f3ff1ff70e281eb" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "nombre" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "direccion" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "telefono" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "FK_d92091990290fec5abcf98256ba" FOREIGN KEY ("empresaId") REFERENCES "empresa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD CONSTRAINT "FK_2afa1a9f64adb52769a88b8bcf1" FOREIGN KEY ("proyectoId") REFERENCES "proyecto"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD CONSTRAINT "FK_9666f8f34f904ed0c689ccbbf63" FOREIGN KEY ("empleadoId") REFERENCES "empleado"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "FK_d7ca17aadfa6ac12abaa516aebb" FOREIGN KEY ("empresaId") REFERENCES "empresa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_7c32234b5a54ad7a2a848a3e0d4" FOREIGN KEY ("empresaId") REFERENCES "empresa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_7c32234b5a54ad7a2a848a3e0d4"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "FK_d7ca17aadfa6ac12abaa516aebb"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP CONSTRAINT "FK_9666f8f34f904ed0c689ccbbf63"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP CONSTRAINT "FK_2afa1a9f64adb52769a88b8bcf1"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "FK_d92091990290fec5abcf98256ba"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "telefono" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "direccion"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "direccion" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "nombre" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "password" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "UQ_35aafb5ad218f3ff1ff70e281eb"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "username" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "staff_username_key" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "puesto"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "puesto" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "telefono" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "UQ_902985a964245652d5e3a0f5f6a"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "staff_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "apellidos"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "apellidos" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "UQ_672277994ca3023846620f5c7a2"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "username" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "empleado_username_key" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "telefono" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "empleado_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "apellidos"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "apellidos" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "estado" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "nombre" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "estado" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "proyecto" ALTER COLUMN "presupuesto" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ALTER COLUMN "fecha_fin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ALTER COLUMN "fecha_inicio" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "descripcion" text`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "nombre" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "PK_bee78e8f1760ccf9cff402118a6"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "empresaId"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "PK_e4ee98bb552756c180aec1e854a"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "empresaId"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "fechaContratacion"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP CONSTRAINT "PK_d15e7688d5ed23e9fdb570b2e5d"`);
        await queryRunner.query(`ALTER TABLE "empleado" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "empleadoId"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "proyectoId"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "fechaFin"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "fechaInicio"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP CONSTRAINT "PK_52df0f8fc74f81d0531ad890f0e"`);
        await queryRunner.query(`ALTER TABLE "tarea" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "empresaId"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP CONSTRAINT "PK_589bf061fd654da7076e68e1699"`);
        await queryRunner.query(`ALTER TABLE "proyecto" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "uuid" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "empresa_pkey" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "empresa_id" uuid`);
        await queryRunner.query(`ALTER TABLE "staff" ADD "uuid" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "staff_pkey" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "empresa_id" uuid`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "fechacontratacion" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD "uuid" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "empleado_pkey" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "empleado_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "proyecto_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "fechafin" date`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "fechainicio" date`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD "uuid" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD CONSTRAINT "tarea_pkey" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "empresa_id" uuid`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD "uuid" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "proyecto_pkey" PRIMARY KEY ("uuid")`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "fk_empresa_staff" FOREIGN KEY ("empresa_id") REFERENCES "empresa"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empleado" ADD CONSTRAINT "fk_empresa" FOREIGN KEY ("empresa_id") REFERENCES "empresa"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD CONSTRAINT "fk_empleado" FOREIGN KEY ("empleado_id") REFERENCES "empleado"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tarea" ADD CONSTRAINT "fk_proyecto" FOREIGN KEY ("proyecto_id") REFERENCES "proyecto"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proyecto" ADD CONSTRAINT "proyecto_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "empresa"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
