# Usa una imagen base de Node.js
FROM node:18-alpine AS builder

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY ./package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Establece la variable de entorno para el frontend
ENV NEXT_PUBLIC_BACKEND_API_URL=$BACKEND_API_URL

# Compila el proyecto
RUN npm run build

# Usa una segunda etapa para la producción
FROM node:18-alpine AS production

WORKDIR /app

# Copia los archivos compilados desde el builder
COPY --from=builder /app/.next /app/.next
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Exponer el puerto para la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
