# Usa una imagen base de node.js
FROM node:18-alpine AS builder

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY ./package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Genera la build de producción
RUN npm run build

# Usa una imagen ligera para producción
FROM node:18-alpine

WORKDIR /app

# Copia los archivos generados desde el builder
COPY --from=builder /app .

# Expone el puerto
EXPOSE 3000

# Comando de inicio
CMD ["npm", "start"]
