# Usa una imagen base de Node.js para la fase de build
FROM node:18-alpine AS builder

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código fuente del frontend al contenedor
COPY . .

# Compila el proyecto
RUN npm run build

# Usa una segunda etapa para la producción
FROM node:18-alpine AS production

# Define el directorio de trabajo para producción
WORKDIR /app

# Copia los archivos compilados y necesarios desde el builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Exponer el puerto para la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "run", "start"]

